### ISSUE TITLE
Could you please add examples? to the readme?

### ISSUE THREAD

**Issue by comuneoOrg** [ZachHandley/AppwriteUtils#1]
Thanks for creating this appwrite migration!
I find it super useful, and i believe it would be easier if there would usage examples.. how to use it... from your point of view. 
I had to go through it for a while, and it took me some time to get the idea of how to use it, which i'll be experimenting now

Thanks for your effort creating this !!

**Comment by ZachHandley** [comment]
For sure, give me a day or so and I'll update the ReadMe with examples

**Comment by ZachHandley** [comment]
@comuneoOrg I published it to a package and made the config *much* easier to understand, and added an examples folder too so you don't need to try that hard 😄 [Appwrite Utils](https://www.npmjs.com/package/appwrite-utils)
