### ISSUE TITLE
npm ERR! could not determine executable to run on Windows 11

### ISSUE THREAD

**Issue by basrioglumehmet** [ZachHandley/AppwriteUtils#2]
I tried all ways to run the cli. On Windows 11, cannot recognize the commands. How can i fix that? Already installed global package on my desktop (npm ERR! could not determine executable to run , 'appwrite-utils-cli' is not recognized as an internal or external command,
operable program or batch file.)

**Comment by ZachHandley** [comment]
hey sorry, I updated the `README` so it should be more clear

I usually run it by using `npx --package=appwrite-utils-cli@latest appwrite-migrate -- --arg1 --arg2`, please reopen this if you need any other help!
