### ISSUE TITLE
bug: Enums sync as string attributes

### ISSUE THREAD

**Issue by pingu2k4** [ZachHandley/AppwriteUtils#4]
- Create a collection within a DB.
- Create an enum attribute and give it some options
- run `appwrite-migrate --sync`
- Check the config file, and note that the enum attribute is listed as a string attribute instead.

**Comment by ZachHandley** [comment]
I shall fix, thank you :)

**Comment by ZachHandley** [comment]
@pingu2k4 I have resolved this bug
